# Setup
title:               Arpit's blog
description:         'A blog where I hopefully put things I find interesting'
url:                 https://arpit-saxena.github.io
baseurl:             '/blog'
paginate:            5
permalink:           pretty
highlighter:         rouge

markdown: kramdown
kramdown:
   math_engine: mathjax

# About/contact
author:
  name:              Arpit Saxena
  url:               https://github.com/arpit-saxena
  email:             arpit.saxena2000@yahoo.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
